name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PAT}}    
      run: |
        echo "$MY_PASSWORD" | docker login --username $DOCKER_USE --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag larentals:$(date +%s)

    - name: Docker Push
      run: docker push strayingfromthepath/larentals
