name: Pull image and restart container
on:
 # Only trigger when the Docker build completes
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        #fingerprint: ${{ secrets.SSH_FINGERPRINT }}
        script: docker pull strayingfromthepath/larentals && docker restart wheretolivedotla
